import random
import time

'''
DISCLAIMER! The file 'players.txt' was generated by AI. All the players names and their informations were generated by ChatGPT. I only changed special letters like ć to a normal c.
I used AI, because it was quick and it would have been a repetetive task without it. And I wanted to focus on programming, not on searching on thousand websites. Please understand my decision and have fun with this game!
'''

characterizations_text = ["Same skin color", "Same conference", "Same team", "Same Allstar status", "Same MVP status", "Same shooting hand", "Same main position"]
player = []
players = []
player_names = []
guesses = 0
guessed = False

def choose_player():
    global players
    lines = ""
    with open('players.txt') as f:
        lines = (f.read().rstrip())
    f.close()
    lines = lines.split("\n")
    lines.pop(0)
    players = lines
    for e in lines:
        player_names.append(e.split(" # ")[0])
    
    random_player = random.choice(lines).split(" # ")
    return random_player
    
def get_similarities(guess):
    simis = []
    char_p1 = players[player_names.index(guess)].split(" # ")[1:]
    char_p2 = players[player_names.index(player[0])].split(" # ")[1:]
    
    for e in char_p1:
        if e in char_p2:
            simis.append(characterizations_text[char_p1.index(e)])
    
    if len(simis) == 0:
        print("No same characterizations...")
        
    else:
        print("Their similarities:")
        for l in simis:
            print(l)
    print()
    print("Guess again")
    print()


def start():
    global player
    global guessed
    global player_names
    global guesses
    player = choose_player()
    print()
    print("Welcome to Guess The NBA Player!")
    print("Let's think of a NBA player...")
    time.sleep(1)
    print("I got one!\n Now start guessing.")
    print("Name a NBA player, when it's not the right one, I will say which characteristics are the same. Like team or conference...")
    print("Try to guess with least guesses as you can!")
    print("When you want to give up, type 'give up'.")
    print("")
    while not guessed:
        guess = input("Your guess:\n")
        if guess == "Give up" or guess == "give up":
            print("Well... The player was:")
            time.sleep(0.5)
            print(player[0])
            break
        if guess not in player_names:
            print("Hm. I don't know this player. Please guess someone else.")
        else:
            guesses += 1
            if guess == player[0]:
                print("Yes Sir! You got it!")
                print("You needed "+str(guesses)+" guesses")
                guessed = True
                print()
            else:
                print("No.")
                get_similarities(guess)


if __name__ == "__main__":
    start()